---
booktitle: 'Proceedings of the 3rd International Workshop on Big Data, Streams and
  Heterogeneous Source Mining: Algorithms, Systems, Programming Models and Applications'
title: Proceedings of Machine Learning Research
volume: 36
year: '2014'
start: 2014-08-24
end: 2014-08-24
published: 2014-08-13
shortname: BigMine
sections:
- name: preface
  title: Front Matter
- name: default
  title: Accepted Papers
layout: proceedings
series: Proceedings of Machine Learning Research
issn: 1938-7228
id: BIGMINE-2014
month: 0
tex_title: 'Workshop on Big Data, Streams and Heterogeneous Source Mining: Algorithms,
  Systems, Programming Models and Applications'
cycles: false
editor:
- given: Wei
  family: Fan
- given: Albert
  family: Bifet
- given: Qiang
  family: Yang
- given: Philip S.
  family: Yu
description: |
  Proceedings of the 3rd International Workshop on Big Data, Streams and Heterogeneous Source Mining: Algorithms, Systems, Programming Models and Applications
    Held in New York, New York, USA on 24 August 2014

  Published as Volume 36 by the Proceedings of Machine Learning Research on 13 August 2014.

  Volume Edited by:
    Wei Fan
    Albert Bifet
    Qiang Yang
    Philip S. Yu

  Series Editors:
    Neil D. Lawrence
    Mark Reid
date_str: 24 Aug
url: http://proceedings.mlr.press
author:
  name: PMLR
baseurl: "/v36"
twitter_username: MLResearchPress
github_username: mlresearch
markdown: kramdown
style: pmlr
plugins:
- jekyll-feed
- jekyll-seo-tag
- jekyll-remote-theme
remote_theme: lawrennd/proceedings
permalink: "/:title.html"
ghub:
  edit: true
  repository: v36
display:
  copy_button:
    bibtex: true
    endnote: true
    apa: true
    ris: true
  comments: false
email: ''
conference:
  name: 'Proceedings of the 3rd International Workshop on Big Data, Streams and Heterogeneous
    Source Mining: Algorithms, Systems, Programming Models and Applications'
  url: http://bigdata-mining.org/bigmine-14/
  location: New York, New York, USA
  dates:
  - 2014-08-24
  number: 3
analytics:
  google:
    tracking_id: UA-92432422-1
orig_bibfile: "/Users/neil/mlresearch/bibtex.bib"
# Site settings
# Original source:  /Users/neil/mlresearch/bibtex.bib
